portfolio: Bill Lumberg

theme: light
patternImage: circuit.svg

socialMedia:
  - name: GitHub
    url: https://github.com/uvacoder
    image: github.svg

  - name: Twitter
    url: https://twitter.com/AlecCam43544378
    image: twitter.svg
    
  - name: LinkedIn
    url: https://linkedin.com/en/alecbcampbell
    image: linkedin.svg

projects:
  - name: My Links
    url: https://abclinks.vercel.app/
    image: about-me.svg

  - name: GitHub
    url: https://github.com/uvacoder
    image: responsive-snake.png

  - name: Shrink Me
    url: https://shrinkme.app
    image: shrink-me.svg
    backgroundColor: \#fefefe

terms:
  name: Your name
  website: https://crafted.link

privacy:
  name: Richard Kimble
  address: Virginia
  mail: freeunioncoder@gmail.com
  phone: Your number e.g. +1-123-456-7890
